name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23
    
    - name: Run Tests
      run: go test -v ./...

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag your-dockerhub-username/your-repo-name:${{ github.sha }}
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ 'secrets.DOCKERHUB_USERNAME' }}
        password: ${{ 'secrets.DOCKERHUB_TOKEN' }}
        
    - name: Push to DockerHub
      run: docker push your-dockerhub-username/your-repo-name:${{ github.sha }}
